#!/bin/bash

#cd /home/SDI/SDI/gerador


#ZONE=/etc/bind/prd.zone
#NRES="$(awk '{print $4}' $ZONE |cut -d: -f1|sed -e "s/;//"|sort -u)"
NRES=$(cd NRES; echo *;cd - &>/dev/null)
NONRES=$(ls NRES|wc -l)
COUNT=0
for NRE in $NRES; do
#for NRE in APUCARANA; do
    ((COUNT++))
    printf "Starting: $NRE( $COUNT/$NONRES).\n"
    sleep 0.5
    DAEMON=true bash launchsdi.sh "$(awk '{print $1}' NRES/$NRE)"
    #sleep $(wc -l NRES/$NRE|awk '{print $1}')
    printf "Done: $NRE( $COUNT/$NONRES)\n"
    sleep 0.5
done

printf "Tudo Lancado.\n"
