#!/bin/bash

PREFIX=$(dirname $0)

function usage () {
    echo "Usage:"
    echo "  $0 [options]"
    echo "Options:"
    echo -ne "  --start\n\tStart SDI.\n"
    echo -ne "  --stop\n\tStop SDI\n"
    echo -ne "  --restart\n\tRestart SDI\n"
    echo -ne "  --sync-data\n\tSyncronize fast data dir with data dir\n"
}

TEMP=$(getopt -o hsScR \
       --long 'help,start,stop,restart,sync-data' \
       -n 'sdictl' -- "$@")

eval set -- "$TEMP"

while true; do
    case "$1" in
        --start)
            bash $PREFIX/startsdi.sh
            break ;;
        --stop)
            bash $PREFIX/sync.sh
            bash $PREFIX/stopsdi.sh
            break ;;
        --restart)
            bash $PREFIX/sync.sh
            bash $PREFIX/stopsdi.sh
            bash $PREFIX/startsdi.sh
            break ;;
        --sync-data)
            bash $PREFIX/sync.sh
            break ;;
        *)
            usage
            break ;;
    esac
done
