#!/bin/bash
# Functions defined here can be used by others scripts

# function used to kill the childs of a process
# you must not remove this function, it's essential
# to close hosts connections correctly
killchilds(){
  local PID=$1
  ps ${PID} &>/dev/null || return
  # needed to stop quickly forking parent from
  # producing child between child killing and parent killing
  kill -stop ${PID}
  for CHILD in $(ps -o pid --no-headers --ppid ${PID}); do
    killchilds ${CHILD}
  done
  kill -9 ${PID}
  wait ${PID} 2>/dev/null
}

# funcion to destroy everything going on here
finisheverything(){
  PID=$$
  for CHILD in $(ps -o pid --no-headers --ppid ${PID}); do
    killchilds ${CHILD}
  done
  rm -Rf "${TEMPDIR}"
  kill -9 ${PID}
}
