#!/bin/bash

UPSEC=$(cat /proc/uptime |cut -d. -f1)
UPDAYS=$((UPSEC/60/60/24))
UPHOURS=$((UPSEC/60/60 - UPDAYS*24))
UPMINUTES=$((UPSEC/60 - UPHOURS*60 - UPDAYS*24*60))
printf "UPTIME+$UPDAYS days, $UPHOURS:$UPMINUTES\n"
